#!/usr/bin/env bash
set -Eeuo pipefail
trap 'echo >&2 "$BASH_SOURCE: line $LINENO: unexpected exit $?"' ERR

# usage: ... <tar> <image>

if ! opts="$(getopt --name "$0" --options '+' --longoptions 'platform:,pull' -- "$@")"; then
	# TODO usage
	exit 1
fi
eval "set -- $opts"

buildArgs=()
while [ "$#" -gt 0 ]; do
	flag="$1"; shift
	case "$flag" in
		--platform) buildArgs+=( "$flag" "$1" ); shift ;;
		--pull) buildArgs+=( "$flag" ) ;;
		--) break ;;
		*) echo >&2 "error: unknown flag '$flag'"; exit 1 ;;
	esac
done

tar="$1"; shift # TODO || usage
from="$1"; shift # TODO || usage

onExit=
defer() {
	local newExit; newExit="$(printf "$@")"
	onExit="$newExit${onExit:+; $onExit}"
	trap "$onExit" EXIT
}

dir="$(mktemp -d -t docker-sbuild.XXXXXX)"
defer 'rm -rf %q' "$dir"

{ echo "FROM $from"; cat; } > "$dir/Dockerfile" <<-'EOF'
	# this should match the package list added to the "buildd" variant in debootstrap and the list installed by sbuild
	# https://salsa.debian.org/installer-team/debootstrap/blob/da5f17904de373cd7a9224ad7cd69c80b3e7e234/scripts/debian-common#L20
	# https://salsa.debian.org/debian/sbuild/blob/fc306f4be0d2c57702c5e234273cd94b1dba094d/bin/sbuild-createchroot#L257-260
	# (we also include "eatmydata" because it's useful for making builds faster)
	RUN set -eux; \
		apt-get update; \
		apt-get install -y --no-install-recommends eatmydata; \
		eatmydata apt-get full-upgrade -y; \
		eatmydata apt-get install -y --no-install-recommends \
			build-essential \
			fakeroot \
			\
	# in case of extra repositories needing https
			ca-certificates \
		; \
		rm -rf /var/lib/apt/lists/*
	COPY .tar-excludes /
EOF
cat > "$dir/.tar-excludes" <<-'EOF'
	./.docker*
	./.tar-excludes
	./etc/hostname
	./etc/hosts
	./etc/resolv.conf
	./proc/**
	./sys/**
EOF
docker build "${buildArgs[@]}" --iidfile "$dir/image.txt" "$dir"
img="$(< "$dir/image.txt")"
#defer 'docker rmi %q > /dev/null' "$img"

# TODO we need to re-inject /etc/hosts into the end result!
# (otherwise things like https://github.com/kubernetes/kube-openapi/blob/f0e62f92d13f418e2732b21c952fd17cab771c75/pkg/validation/validate/jsonschema_test.go#L109 result in "panic: listen tcp: lookup localhost on 172.17.0.1:53: no such host")

# since we already assumed the current Docker host can successfully run the image's binaries, we'll use that here
timestamp="$(docker image inspect --format='{{ .Created }}' "$img")"
docker run --rm --log-driver none --entrypoint bash --env timestamp="$timestamp" "$img" -Eeuo pipefail -c 'tar --create --directory=/ --one-file-system --exclude-from=/.tar-excludes --clamp-mtime --mtime="$timestamp" . ./dev' > "$tar"
tar --list --file "$tar" > /dev/null # very crude "is this tar OK" test

printf '%q created (FROM %q)\n' "$tar" "$from"
