#!/usr/bin/env bash
set -Eeuo pipefail

self="$(basename "$0")"
usage() {
	echo "usage: $self target-incoming-dir/ foo.changes [bar.changes [...]]"
	echo "   eg: $self incoming/ /path/to/foo.dsc"
}
fatal_usage() {
	if [ "$#" -gt 0 ]; then
		echo >&2 "error: $*"
		echo >&2
	fi
	usage >&2
	exit 1
}
[ "$#" -ge 2 ] || fatal_usage "expected at least 2 arguments (got $#)"

targetDirectory="$1"; shift
targetDirectory="$(readlink -ev "$targetDirectory")"

# TODO consider reimplementing this via dget-lite?  it's basically just: for changes; do dget-lite "$targetDirectory" "$changes"; done 😅

for changes; do
	[ -s "$changes" ]

	json="$(dsc-extract-checksums "$changes")"
	dir="$(dirname "$changes")"
	export dir

	if ! (
		set -Eeuo pipefail
		shell="$(jq <<<"$json" -r '.[].bashValidate // error("missing bashValidate from dsc-extract-checksums!")')"
		[ -n "$shell" ]
		cd "$dir"
		eval "$shell"
	); then
		echo >&2 "error: '$changes' appears to be invalid or incomplete!"
		exit 1
	fi

	files="$(jq <<<"$json" -r '
		keys
		| map(env.dir + "/" + . | @sh)
		| join (" ")
	')"
	eval "files=( $files )"
	files+=( "$changes" )

	cp --verbose --dereference --target-directory="$targetDirectory" "${files[@]}"
done
